baseURL = 'https://benmartinbaur.github.io/'
languageCode = 'en-us'
title = 'The Architect | Ben Baur'
theme = 'hugo-theme-stack'

[pagination]
  pagerSize = 5

[params]
  mainSections = ['posts']
  featuredImageField = 'image'
  rssFullContent = true

[params.dateFormat]
  published = 'Jan 02, 2006'
  lastUpdated = 'Jan 02, 2006 15:04 MST'

[params.sidebar]
  emoji = 'ğŸ—ï¸'
  subtitle = 'Thoughts and ideas by Ben'
  avatar = 'img/avatar.jpg'

[params.article]
  math = false
  toc = true
  readingTime = true

[params.comments]
  enabled = false

[params.widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "tag-cloud", params = { limit = 10 } },
  ]
  page = [{ type = "toc" }]

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1
  [menu.main.params]
    icon = 'home'

[[menu.social]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/benmartinbaur'
  weight = 1
  [menu.social.params]
    icon = 'brand-github'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4

enableGitInfo = true
